### ISSUE TITLE
Otter Not Installed on Scicore

### ISSUE THREAD

**Issue by ugurtu** [unibas-marcelluethi/pids-notebooks-fs24#1]
1. I assume that Otter is not installed on Scicore
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 2
      1 # Initialize Otter
----> 2 import otter
      3 grader = otter.Notebook("02-exercise-pids2024.ipynb")

ModuleNotFoundError: No module named 'otter'
```
2. Then we need also to ensure that module assert is installed on Scicore

**Comment by marcelluethi** [comment]
Good catch. I forgot to add the assert files to the repository.
Otter should be installed if you select the right kernel (pids_2023)

I added the assert file to the repository and checked, that with the right kernel the tests run. 
I will change the name of the kernels directly in the notebook, before submitting them to the students. We cannot easily do it now, as it is stored in the metadata and will be overwritten whenever I make changes on my local machine (which does not have a kernel with that name).
